### ISSUE TITLE
Alignment of the Hero text

### ISSUE THREAD

**Issue by Ononero** [zuri-training/qr_gen_team60#132]
on the Hero Section, the title:

'The #1xyz'
and the 
'QR Generator Code generator for everyone'

the text are not aligned

**Comment by Elizzy01** [comment]
The Alignment is okay. Check it out; the active state of the page have also been implemented.
![Screenshot 2022-08-12 184748](https://user-images.githubusercontent.com/98459984/184415110-bbd38ebc-3ac9-4b8f-bd07-088bfdb96d15.png)

**Comment by Ononero** [comment]
Great...and thumbs up for the prompt resolution
