### ISSUE TITLE
Spacing between Primay and Secondary Button on Hero/Header

### ISSUE THREAD

**Issue by Ononero** [zuri-training/qr_gen_team60#133]
The Buttons on the Hero section are not well spaced as designed.

You may wish to consult the the Homepage image and the design on Zeplin

Well-done Guys,
Great job

**Comment by Elizzy01** [comment]
This has also been checked, kindly verify.
![Screenshot 2022-08-12 175205](https://user-images.githubusercontent.com/98459984/184410304-8742ba3c-18ac-475c-a2ff-4a2045e1b7c4.png)

**Comment by Ononero** [comment]
Great job
