### ISSUE TITLE
Site Colors

### ISSUE THREAD

**Issue by Ononero** [zuri-training/qr_gen_team60#134]
Hello Dev Team,

Great job guys. Please can you confirm ha t the colors used for the Hero section are as follows? :

Pry Button: #092c64
Hero section bg: #d0dff6

**Comment by Elizzy01** [comment]
![Screenshot 2022-08-12 175205](https://user-images.githubusercontent.com/98459984/184406798-d10f137b-4343-4f7b-8de5-7f7222fac8a5.png)

These are the exact colours used.

**Comment by Ononero** [comment]
K. The previous shot should shades closer to purple...maybe its camera
reflections

**Comment by Elizzy01** [comment]
Yeah, maybe some screen effects set by the user
